plugins {
    id 'com.android.application'
}

android {
    namespace 'org.glfw.example'
    compileSdkVersion 34

    defaultConfig {
        applicationId 'org.glfw.example'
        minSdkVersion 24
        targetSdkVersion 34
        versionCode 1
        versionName '1.0'
        // NativeActivity will load libandroid_triangle.so
        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    externalNativeBuild {
        cmake {
            path file('CMakeLists.txt')
            version '3.22.1'
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
}
